#lang racket

(require slideshow/pict)
(require racket/runtime-path)

(provide wolf bear bat lion player cheese gold sword armour empty-set lambda-image programming-text-book state-machine arduino flip-flop drracket hash-table venn-diagram proper-list tree graph player-on-map)

(define-runtime-path wolf-file "images/wolf.png")
(define-runtime-path bear-file "images/bear.png")
(define-runtime-path bat-file "images/bat.png")
(define-runtime-path lion-file "images/lion.png")
(define-runtime-path player-file "images/explorer.png")
(define-runtime-path cheese-file "images/cheese.png")
(define-runtime-path gold-file "images/gold.png")
(define-runtime-path sword-file "images/sword.png")
(define-runtime-path armour-file "images/armour.png")


(define-runtime-path empty-set-file "images/empty-set.png")
(define-runtime-path lambda-file "images/lambda.png")
(define-runtime-path programming-textbook-file "images/realm-of-racket.png")
(define-runtime-path state-machine-file "images/state-machine.png")
(define-runtime-path arduino-file "images/arduino.png")
(define-runtime-path flip-flop-file "images/flip-flop.png")
(define-runtime-path drracket-file "images/drracket.png")
(define-runtime-path tree-file "images/armour.png")
(define-runtime-path graph-file "images/graph.png")
(define-runtime-path list-file "images/list.png")
(define-runtime-path venn-diagram-file "images/venn_diagram.png")
(define-runtime-path hash-table-file "images/hash-table.png")
(define-runtime-path player-on-map-file "images/player-on-map.png")


(define wolf (bitmap wolf-file))
(define bear (bitmap bear-file)) 
(define bat (bitmap bat-file))
(define lion (bitmap lion-file))
(define player (bitmap player-file))
(define cheese (bitmap cheese-file))
(define gold (bitmap gold-file))
(define sword (bitmap sword-file))
(define armour (bitmap armour-file))

(define empty-set (bitmap empty-set-file))
(define lambda-image (bitmap lambda-file))
(define programming-text-book (bitmap programming-textbook-file))
(define state-machine (bitmap state-machine-file))
(define arduino (bitmap arduino-file))
(define flip-flop (bitmap flip-flop-file))
(define drracket (bitmap drracket-file))
(define tree (bitmap tree-file))
(define graph (bitmap graph-file))
(define proper-list (bitmap list-file))
(define venn-diagram (bitmap venn-diagram-file))
(define hash-table (bitmap hash-table-file))
(define player-on-map (bitmap player-on-map-file))